### ISSUE TITLE
SSH authentication is not supported

### ISSUE THREAD

**Issue by pmatulis** [canonical-documentation/canonical-doc-utils#8]
It looks like SSH authentication is not supported.

```
Enter branch number, or #<> to choose a specific branch: 
Number:2
cloning fork from ssh://git@github.com/pmatulis/maas-docs
Traceback (most recent call last):
  File "/snap/canonical-doc-utils/6/bin/docs-backport", line 11, in <module>
    load_entry_point('CanonicalDocUtils==0.2.15', 'console_scripts', 'docs-backport')()
  File "/snap/canonical-doc-utils/6/lib/python3.5/site-packages/CanonicalDocUtils/cli/bporter.py", line 137, in main
    sync(fork_url, upstream_url, branchname, False)
  File "/snap/canonical-doc-utils/6/lib/python3.5/site-packages/CanonicalDocUtils/cli/utils.py", line 30, in sync
    git.clone(fork_url)
  File "/snap/canonical-doc-utils/6/lib/python3.5/site-packages/sh.py", line 1427, in __call__
    return RunningCommand(cmd, call_args, stdin, stdout, stderr)
  File "/snap/canonical-doc-utils/6/lib/python3.5/site-packages/sh.py", line 774, in __init__
    self.wait()
  File "/snap/canonical-doc-utils/6/lib/python3.5/site-packages/sh.py", line 792, in wait
    self.handle_command_exit_code(exit_code)
  File "/snap/canonical-doc-utils/6/lib/python3.5/site-packages/sh.py", line 815, in handle_command_exit_code
    raise exc
sh.ErrorReturnCode_128: 

  RAN: /usr/bin/git clone ssh://git@github.com/pmatulis/maas-docs

  STDOUT:


  STDERR:
Cloning into 'maas-docs'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists

**Comment by evilnick** [comment]
SSH is very much supported - in fact it is the only thing that is supported.

This error reveals that the command:
        git clone ssh://git@github.com/pmatulis/maas-docs
has failed. This is the same as if you had run the above yourself from the command line
Can you confirm that running this command works if you enter it manually?

IIRC the issue degville had regarded github being an unknown host, so he had to run it manually once to add the host to the known hosts file

**Comment by pmatulis** [comment]
I believe my problem was related to a malevolent ssh agent. Disregard for now.
